server:
  port: 8080
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

spring:
  datasource:
    url: jdbc:mysql://8.140.205.108:6003/interview_qa_helper?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: QQmima123
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.interview.helper.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.interview.helper: debug
    org.springframework: info
    org.mybatis: debug
